CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    CPF_CNPJ VARCHAR(255),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PRODUTOS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    QTDE INTEGER,
    PRECO DOUBLE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PEDIDOS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER REFERENCES USERS(ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTOS(ID),
    QTDE INTEGER,
    PRECO DOUBLE
);
